whitelist_rules:
  - line_length
line_length: 110
excluded:
  - Carthage/
  - Frameworks/
  - Kickstarter-iOS.playground/
  - Library/Strings.swift
  - bin/strings.swift
  - bin/StringsScript/Sources/StringsScriptCore/Secrets.swift
  - vendor
reporter: "xcode"
custom_rules:
  localized_lensing:
    name: "Localized Lensing"
    regex: '\.~\s+Strings\s*\.'
    message: "Capture calls to `Strings` functions using `%~ { _ in Strings... }`"
    severity: error
  record_mode_prohibited:
    name: "Record Mode Prohibited"
    regex: "recordMode = true"
    message: "Do not use `recordMode = true`."
    severity: warning
